name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet restore BookVerse/src/Library.WebAPI/Library.WebAPI.csproj
      - run: dotnet build --no-restore BookVerse/src/Library.WebAPI/Library.WebAPI.csproj
      - run: dotnet test BookVerse/tests/Library.UnitTests/Library.UnitTests.csproj
